# https://bettercodehub.com

# Search for project directories in the subdirs too (level 2).
component_depth: 2

languages:
  - name: python

    production:
      exclude:
        - /example_settings.py
        - /test_settings.py
        - /setup.py
        - /planb/default_settings.py
        - .*/migrations/.*
        - .*/test_*\.py
        - .*/tests.*\.py

    test:
      include:
        - .*/test_*\.py
        - .*/tests.*\.py
