language: python

services:
  - redis-server

addons:
  apt:
    packages:
    - python-docutils

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

matrix:
  include:
    - python: "3.9"
      env: TOXENV=flake8

install: pip install tox-travis

script: tox -- -v
